config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/google_oauth2/callback', to: 'sessions#create'
  delete '/session', to: 'sessions#delete'

  # dashboard
  get '/greenhouse', to: 'users#show'
  get '/about', to: 'about#index'
  get '/ferns/:id/water', to: 'ferns#edit', as: :water_fern
  get '/ferns/:id/fertilize', to: 'ferns/activities#index', as: :fertilize_fern

  resources :ferns, only: %i[new create show destroy update] do
    resources :stats, controller: 'ferns/stats', only: :index
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :validate_user, only: %i[new show]
  helper_method :current_user
  def current_user
    @current_user ||= session[:user] if session[:user]
  end

  def validate_user
    return if current_user

    flash[:error] = 'You must be logged in to access this page'
    redirect_to root_path
  end
end

app/controllers/ferns/activities_controller.rb
class Ferns::ActivitiesController < ApplicationController
  def index
    @fern = FernFacade.find_fern(current_user['uid'], params[:id])
    @activity = ActivityFacade.get_an_activity
  end
end

app/controllers/ferns/activity_controller.rb
class Ferns::ActivityController < ApplicationController
  def index
    @fern = FernFacade.find_fern(current_user['uid'], params[:id])
    @activity = ActivityFacade.get_an_activity
  end
end

app/controllers/ferns/stats_controller.rb
class Ferns::StatsController < ApplicationController
  def index
    @fern = FernFacade.get_fern_stats(current_user['uid'], params[:fern_id])
  end
end

app/controllers/ferns_controller.rb
class FernsController < ApplicationController
  def new; end

  def create
    created_fern = FernService.create_fern(current_user['uid'], fern_params)
    if created_fern.body['error'] == 'error'
      flash[:error] = "Please fill all of your fern's information out"
      render :new
    else
      redirect_to greenhouse_path
      flash[:success] = 'Congratulations on your new fern!'
    end
  end

  def show
    @fern = FernFacade.find_fern(current_user['uid'], params[:id])
    return if @fern.user_id == current_user['uid']

    flash[:error] = 'Focus on your own Ferns for now!'
    redirect_to greenhouse_path
  end

  def destroy
    fern = FernFacade.find_fern(current_user['uid'], params[:id])
    FernFacade.delete_fern(current_user['uid'], params[:id])
    redirect_to greenhouse_path
    flash[:success] = "#{fern.name} has been composted! Boundaries are healthy, good for you!"
  end

  def edit
    @fern = FernFacade.find_fern(current_user['uid'], params[:id])
  end

  def update
    if valid_interaction?
      update_for_water
    elsif params[:activity]
      update_for_fertilize
    else
      flash[:error] = "Interaction can't be blank"
      redirect_to water_fern_path(params[:id])
    end
  end

  private

  def valid_interaction?
    return unless params[:interaction]

    params[:interaction].delete(' ') != '' && params[:interaction].length >= 2
  end

  def fern_params
    params.permit(:name, :shelf, :interaction, :preferred_contact_method)
  end

  def fertilize_params
    params.permit(:activity)
  end

  def update_for_water
    response = FernService.update_fern(current_user['uid'], params[:id], fern_params)
    flash[:success] = water_success_message(response)
    redirect_to fern_path(params[:id])
  end

  def update_for_fertilize
    FernService.update_fern(current_user['uid'], params[:id], fertilize_params)
    flash[:success] = 'Fertilized!'
    redirect_to fern_path(params[:id])
  end

  def water_success_message(response)
    parsed_response = JSON.parse(response.body, symbolize_names: true)
    interaction = Interaction.new(parsed_response[:included][0])
    interaction.water_message
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.new(user_information)
    session[:user] = user.raw_data
    create_info = session[:user]
    create_info[:google_id] = create_info[:uid]
    UserFacade.create_user(create_info)

    redirect_to '/greenhouse'
  end

  def delete
    session[:user] = nil
    redirect_to root_path
  end

  private

  def user_information
    request.env['omniauth.auth']
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  def new

  end

  def create
    created_shelf = FernService.create_shelf(current_user['uid'], shelf_params)
    # binding.pry
    if created_shelf.body['error'] == 'error'
      flash[:error] = "Please fill out all of the shelf's information out"
      render :new
    else
      redirect_to greenhouse_path
      flash[:success] = 'Congratulations on your new shelf! Plant a fern to add to the shelf and get watering!'
    end
  end

  private

  def shelf_params
    params.permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @shelves = ShelfFacade.user_shelves(current_user['uid'])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class='container pots'>
  <div class='col-sm-2 text-center'><%= image_tag("love-fern-1_720.png", height: '128') %></div>
  <div class='col-sm-2 text-center'><%= image_tag("love-fern-2_720.png", height: '128') %></div>
  <div class='col-sm-2 text-center'><%= image_tag("love-fern-3_720.png", height: '128') %></div>
  <div class='col-sm-2 text-center'><%= image_tag("love-fern-4_720.png", height: '128') %></div>
  <div class='col-sm-2 text-center'><%= image_tag("love-fern-5_720.png", height: '128') %></div>
</div>
<%= image_tag("hr-vine-thinner.png", class: "hr-vine" ) %><br>
<h2>About</h2>
<p>Love Fern is an application that allows users to cultivate relationships with important people in their lives by taking care of a fern.</p>
<p>
<b>Water your fern</b> by copying and pasting a message or conversation with that person, 
and Love Fern will automatically analyze the message and update the fern graphic to reflect its current health.
</p>
<%= image_tag("hr-vine-thinner.png", class: "hr-vine" ) %><br>
<%= render partial: '/partials/instructions' %>
<%= image_tag("hr-vine-thinner.png", class: "hr-vine" ) %><br>
<h2>GitHub & Heroku Links</h2>
<ul>
  <li><a href='https://github.com/love-fern'>🪴🤝🪴 Love Fern Organization</a></li>
  <li><a href='https://github.com/love-fern/love_fern_fe'>🪡 Front End Repository</a></li>
  <li><a href='https://github.com/love-fern/love_fern_be'>🧵 Back End Repository</a></li>
  <li><a href='https://fernando.herokuapp.com/'>🔌 "Fernando" (Our Backend Service)</a></li>
</ul>

<%= image_tag("hr-vine-thinner.png", class: "hr-vine" ) %><br>
<h2>Love Fern Team</h2>
<div class='container'>
  <div class="row">
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-aongaro.png") %><br>
      <p class='about-names'>
        Anthony Ongaro
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/ajongaro'>GitHub</a> | <a href='https://www.linkedin.com/in/ajongaro/'>LinkedIn</a> ]
      </p>
    </div>
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-atallent.png") %><br>
      <p class='about-names'>
        Anthony Blackwell Tallent
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/anthonytallent'>GitHub</a> | <a href='https://www.linkedin.com/in/anthony-blackwell-tallent-b36916255/'>LinkedIn</a> ]
      </p>
    </div>
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-brohrig.png") %><br>
      <p class='about-names'>
        Brady Rohrig
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/BRohrig'>GitHub</a> | <a href='https://www.linkedin.com/in/brady-rohrig-5305a923/'>LinkedIn</a> ]
      </p>
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-dlayton.png") %><br>
      <p class='about-names'>
        Drew Layton
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/dlayton66'> GitHub</a> | <a href='https://www.linkedin.com/in/drew-layton-6009a4153/'>LinkedIn</a> ]
      </p>
    </div>
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-jseymour.png") %><br>
      <p class='about-names'>
        J Seymour
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/JustJakeSeymour'>GitHub</a> | <a href='https://www.linkedin.com/in/j-seymour/'>LinkedIn</a> ]
      </p>
    </div>
    <div class='col-sm-4 text-center'>
      <%= image_tag("team-scox.png") %><br>
      <p class='about-names'>
        Samuel Cox
      </p>
      <p class='bio-links'>
        [ <a href='https://github.com/sambcox'>GitHub</a> | <a href='https://www.linkedin.com/in/samuel-bingham-cox/'>LinkedIn</a> ]
      </p>
    </div>
  </div>
</div>
<%= image_tag("hr-vine-thinner.png", class: "hr-vine" ) %><br>
<div class='container'>
  <h2>Goals</h2>

  <p>Love Fern was germinated to satisfy the requirements for a Turing Backend Mod 3
  group project, Consultancy. Official project requirements can be read 
  <a href='https://backend.turing.edu/module3/projects/consultancy/'>here</a>.<p>


  <h3>Learning Goals</h3>
  <ul>
    <li>Implement OAuth2 with OmniAuth to allow users to sign in with Google.</li>
    <li>Using Service Oriented Architecture</li>
    <li>Use of HTML, CSS, and JavaScript via Bootstrap to design a pleasing front-end aesthetic.</li>
    <li>Building a full-scale application from scratch using service-oriented architecture.</li>
  </ul>

  <h3>Future Goals</h3>
  <ul>
    <li>Implement "watering frequency," which indicates how often a user wishes to interact with their fern before it starts to decay.</li>
    <li>Add more detailed stats to the fern show page, including time since last contact and information about the nature of that contact.</li>
    <li>Add the ability to search for a fern by name and order ferns by health.</li>
    <li>Suggest multiple activities and gestures corresponding to varying levels of care needed for the fern.</li>
    <li>Build out the fern health algorithm to incorporate activities and gifts, as well as a more nuanced interpretation of Google's sentiment analysis.</li>
  </ul>

  <h3>Known Issues</h3>
  <ul>
    <li>The fertilize feature currently suggests a random activity to do with your fern. Please consider real life consequences are not our responsibility if you do ask your fern to do this activity.</li>
  </ul>
</div>

app/views/ferns/activities/index.html.erb
<div class='container text-center'>
  <h2>Fertilize Your Fern!</h2>
  <% if @fern.health < 3 %>
    <h3>Oh no! Your relationship with <%= @fern.name %> is nearly a husk. It needs some real CPR!</h3>
  <% elsif @fern.health < 5 %>
    <h3>Yikes! Your relationship with <%= @fern.name %> isn't looking too healthy.</h3>
  <% elsif @fern.health < 7 %>
    <h3>Your relationship with <%= @fern.name %> isn't too bad, but it could use a little work!</h3>
  <% else %>
    <h3>Your relationship with <%= @fern.name %> is looking great, but it is always important to fertilize!</h3>
  <% end %>

  <%= link_to image_tag(@fern.image, class: 'fern-show-image', alt: 'fern health image', id: "fern-#{@fern.id}"), fern_path(@fern.id) %><br>

  <h3>Maybe you could... <%= @activity.activity %> together!</h3>
  <div class='spacer-2'>
  </div>
  <div class='row'>
    <div class='col-sm-2'>
    </div>
    <div class='col-sm-2'>
      <%= button_to "Sure!", fern_path(@fern.id), params: { activity: @activity.activity }, method: :patch, class: 'btn btn-lg btn-primary' %>
    </div>
    <div class='col-sm-4'>
      <%= button_to "Find Something Else", fertilize_fern_path(@fern.id), method: :get, class: 'btn btn-lg btn-primary' %>
    </div>
    <div class='col-sm-2'>
      <%= button_to "Maybe Not...", fern_path(@fern.id), method: :get, class: 'btn btn-lg btn-primary' %>
    </div>
    <div class='col-sm-2'>
    </div>
  </div>
</div>

app/views/ferns/edit.html.erb
<div class='container text-center'>
  <h2>
    <%= @fern.name %>'s Fern
  </h2>
</div>

<div id="disclaimer-warning" class='container text-center'>
  <h4>Disclaimer:</h4>
  <p>Interaction analysis is done by an advanced machine learning model. It is not perfect.
  Have fun, water your fern, and <b>don't take it too seriously.</b><br>
  </p>
</div>
<p></p>
<div class='container'>
  <div class='col-sm-4'>
  </div>
  <div class='col-sm-4 text-center'>
    <h4>Add Interaction</h4>
    <%= form_with url: fern_path(@fern.id), method: :patch, local: true do |f| %>
      <div class='form-group'>
        <% f.label :interaction, 'Interaction:' %>
        <%= f.text_area :interaction, rows: 8, class: 'form-control' %>
      </div>
      <%= f.submit 'Water Fern', class: 'btn btn-lg btn-primary' %>
    <% end %>
  </div>
</div>

app/views/ferns/new.html.erb
<div class='text-center'>
  <h2>Plant New Fern</h2>
</div>

<div class='col-sm-4'>
</div>
<div class='col-sm-4'>
  <%= form_with url: '/ferns', method: :post, local: true do |f| %>
    <div class='form-group'>
      <%= f.label :name, 'Name:' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :shelf, 'Shelf:' %>
      <% if @shelves %>
        <%= f.select :shelf, @shelves.map { |shelf| shelf.name } , class: 'form-control' %>
      <% end %>
    </div>

    <div class='form-group'>
      <%= f.label :preferred_contact_method, 'Preferned Contact Method:' %>
      <%= f.text_field :preferred_contact_method, class: 'form-control' %>
    </div>
    <%= f.submit 'Plant!', class: 'btn btn-lg btn-primary' %>
  <% end %>
</div>

app/views/ferns/show.html.erb
<div class="text-center">
  <div class='container'>
    <h2 id='fern-show-header'>
      <%= image_tag(@fern.image, class: 'fern-show-image') %>
      <%= @fern.name %>
    </h2>
  </div>

  <div class='container'>
    <div class='row fern-buttons'>
      <div class='col-sm-4'>
        <%= button_to 'Water Fern', water_fern_path(@fern.id), method: :get, class: 'btn btn-lg btn-primary' %>
      </div>
      <div class='col-sm-4'>
        <%= button_to 'Fertilize Fern', fertilize_fern_path(@fern.id), method: :get, class: 'btn btn-lg btn-primary' %>
      </div>
      <div class='col-sm-4'>
        <%= button_to 'Fern Stats', fern_stats_path(@fern.id), method: :get, class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
  </div>
  <div class="spacer-2"></div>
  <div class='container show-info'>
    <div class="row">
      <div class="col-sm-5">
        <h4>Preferned Contact Method:</h4>
        <%= @fern.preferred_contact_method.capitalize %>
      </div>
      <div class="col-sm-7 text-center">
        <div id="last_3_interactions">
          <h4>Last Three Interactions:</h4>
          <div style="display: inline-block; text-align: left;">
            <% @fern.interactions.each do |interaction| %>
              <%= image_tag(interaction.emoji, class: 'emoji') %>
              <%= interaction.display_message %><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="spacer-2"></div>
  <div class='container'>
    <div>
      <%= button_to 'Compost Fern', fern_path(@fern.id), method: :delete, class: 'btn btn-lg btn-compost', data: {confirm: "Are you sure you want to compost #{@fern.name}?"} %>
    </div>
  </div>
</div>

app/views/ferns/stats/index.html.erb
<h2 id='fern-show-header' class='text-center'>
  <%= link_to image_tag(@fern.image, class: 'fern-show-image'), fern_path(@fern.id) %>
  <%= "#{@fern.name}'s" %>
  <%= "Stats" %>
</h2>

<h3 class='text-center stat-title'>Fern Health</h3>
<br>
<div class='container'>
  <div class='col-sm-2'>
  </div>
  <div class='col-sm-1'>
    <%= image_tag("ferns-axis.png", class: 'ferns-axis') %>
  </div>
  <div class='col-sm-7'>
    <%= line_chart @fern.health_history, curve: false, library: { 
      events: [], 
      scales: {
        x: {
          ticks: {
            display: false
          }
        },
        y: {
          min: 0,
          max: 10,
          ticks: {
            display: false
          }
        }
      } } %>
    
  </div>
  <div class='col-sm-2'>
  </div>
</div>

<br>

<h3 class='text-center stat-title'>Interactions</h3>
<br>
<div class='container'>
  <div class='col-sm-2'>
  </div>
  <div class='col-sm-1'>
    <%= image_tag("emojis/axis.png", class: 'emojis-axis') %>
  </div>
  <div class='col-sm-7'>
    <%= line_chart @fern.interaction_history, curve: false, library: { 
      events: [], 
      scales: {
        x: {
          ticks: {
            display: false
          }
        },
        y: {
          min: -1,
          max: 1.4,
          ticks: {
            display: false
          }
        }
      } } %>
    
  </div>
  <div class='col-sm-2'>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Love Fern - Keep Your Relationships Alive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="container" data-spy="scroll" data-target=".navbar" data-offset="50">
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <% if key == 'error' %>
          <section class="alert alert-danger"><%= value.html_safe %></section>
        <% elsif key == 'notice' %>
          <section class="alert alert-warning"><%= value.html_safe %></section>
        <% elsif key == 'success' %>
          <section class="alert alert-success"><%= value.html_safe %></section>
        <% end %>
      <% end -%>
    <% end %>
    <div class='container'>
      <nav class='navbar navbar-default navbar-fixed-top'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <%= link_to image_tag('love-fern-logo_720.png', size: 30), root_path, class: 'navbar-brand' %>
          </div>
          <ul class='nav navbar-nav'>
            <% if current_user %>
              <li><%= link_to 'Greenhouse', greenhouse_path, class: 'nav-link' %></li>
            <% end %>
            <li><%= link_to 'About', about_path, class: 'nav-link' %></li>
            <% if current_user %>
              <li><%= link_to 'Log Out', session_path, method: :delete, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class='container text-center'>
      <h1>
        Love Fern
      </h1>
    </div>
    <%= yield %>
    <footer class='fixed-bottom'>
      <div class="container text-center">
      <%= image_tag 'plants-footer.png', class: "plant-footer" %>
      </div>
    </footer>
  </body>
</html>

app/views/partials/_instructions.html.erb
<h2>Instructions</h2>
<h3>1. Plant A Fern</h3>
<p>Click <b>Plant a Fern</b> button. Your fern is an important person in your life.
You will be able to name your fern, choose a shelf group, and a preferned contact method.</p>

<h3>2. Water Your Fern</h3>
<p>Love Fern tracks the status of your relationships by analyzing the sentiment of your interactions.
The health of your fern can stay the same, be improved, or deteriorate based on the context and content of your message.
</p>
<p>
Copy and paste a message or conversation with the person your fern represents, and click <b>Water Fern</b>.
</p>
<p>
As your communications continue, keep watering your fern with new messages and work to improve its health with positive interactions!
</p>
<h3>3. Care For Your Fern</h3>
<p>If your fern's health gets too low, a <b>Fertilize Fern</b> button will appear.
Click it to get a suggestion for cool ideas to do together to improve your relationship.
</p>
<h3>4. Compost Your Fern</h3>
<p>If you wish to delete a fern from your greenhouse, no problem!  Simply click the <b>Compost Fern</b> button.
</p>

app/views/partials/_multiple_shelves.html.erb
<% split_index = 0 %>
<% (shelf.ferns.length / 3).times do %>
  <div class="has-bg-img row">
    <% single_shelf = shelf.ferns.slice(split_index, 3) %>
    <% split_index += 3 %>
    <% single_shelf.each do |fern| %>
      <div class="col-sm-4 text-center greenhouse-fern" id=<%=fern.id%>-<%=fern.name%>>
        <%= link_to image_tag(fern.image, class: 'fern-image', alt: 'fern health image', id: "fern-#{fern.id}"), fern_path(fern.id) %><br>
        <p class="fern-name-tag"><%= fern.name %></p>
      </div>
    <% end %>
  </div>
<% end %>
<% if (shelf.ferns.length % 3) > 0 %>
  <div class="has-bg-img row">
    <% single_shelf = shelf.ferns.slice((shelf.ferns.index(shelf.ferns.last) - (shelf.ferns.length % 3) + 1), (shelf.ferns.length % 3)) %>
    <% single_shelf.each do |fern| %>
      <div class="col-sm-4 text-center greenhouse-fern" id=<%=fern.id%>-<%=fern.name%>>
        <%= link_to image_tag(fern.image, class: 'fern-image', alt: 'fern health image', id: "fern-#{fern.id}"), fern_path(fern.id) %><br>
        <p class="fern-name-tag"><%= fern.name %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/partials/_single_shelf.html.erb
<div class="has-bg-img row">
  <% shelf.ferns.each do |fern| %>
    <div class="col-sm-4 text-center greenhouse-fern" id=<%=fern.id%>-<%=fern.name%>>
      <%= link_to image_tag(fern.image, class: 'fern-image', alt: 'fern health image', id: "fern-#{fern.id}"), fern_path(fern.id) %><br>
      <p class="fern-name-tag"><%= fern.name %></p>
    </div>
  <% end %>
</div>

app/views/shelves/new.html.erb
<div class='text-center'>
  <h2>Create Your New Shelf</h2>
</div>

<div class='col-sm-4'>
</div>
<div class='col-sm-4'>
<%= form_with url: '/shelves', method: :post, local: true do |f| %>
  <div class='form-group'>
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit 'Create Shelf!', class: 'btn btn-lg btn-primary' %>
<% end %>
</div>

app/views/users/show.html.erb
<div class='container text-center'>
  <h3>
    <%= current_user['name'] %>'s Greenhouse
  </h3>
  <div class="spacer-2"></div>
  <div class='row greenhouse-buttons'>
    <div class='col-sm-4'>
      <%= button_to 'Plant a Fern', new_fern_path, method: :get, class: 'btn btn-lg btn-primary' %>
    </div>
    <div class='col-sm-4'>
      <%= button_to 'Create a Shelf', new_shelf_path, method: :get, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
  <div class="spacer-1"></div>
</div>
<div class='container'>
  <div class="spacer-1"></div>
  <% if @shelves %>
    <% if @shelves.all? { |shelf| shelf.ferns.empty? } %>
      <%= render partial: '/partials/instructions' %>
    <% end %>
    <% @shelves.each do |shelf| %>
      <% unless shelf.ferns == [] %>
        <div class="shelf-sign text-center">
          <h4 class="shelf"><%= shelf.name %> Shelf</h4>
        </div>
        <div id="<%= shelf.name.downcase %>">
          <% if shelf.ferns.length > 3 %>
            <%= render partial: '/partials/multiple_shelves', locals: { shelf: shelf } %>
          <% else %>
            <%= render partial: '/partials/single_shelf', locals: { shelf: shelf } %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="spacer-1"></div>

<div class="container">
  <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <p>At Love Fern, we believe that <b>strong relationships</b> are the foundation of a happy and fulfilling life.</p>
      <p>That's why we've created a tool that empowers you to <b>build and maintain meaningful connections</b> with the people you care about most.</p>
      <p>Try Love Fern today and see how it can transform your relationships!</p>
    </div>
  <div class="col-sm-2"></div>
</div>

<div class="spacer-2"></div>

<div class="container">
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 text-center">
      <% if current_user %>
        <%= button_to 'Walk to Greenhouse', greenhouse_path, method: :get, class: 'btn btn-lg btn-primary' %>
      <% else %>
        <%= button_to "Continue with Google", "auth/google_oauth2", method: :get, class: 'btn btn-lg btn-primary' %>
      <% end %>
    </div>
  </div>
</div>